//
// Created by Nu lar on 11/16/23.
//

#ifndef CALCULATOR_STATEENUM_H
#define CALCULATOR_STATEENUM_H

enum StateEnum
{
    HIDDEN, FOCUSED, FOUND, HOVERED,
    CLICKED, LAST_STATE
};

#endif //CALCULATOR_STATEENUM_H
